name: abis_gbi_course_cellpose_zarr_2023
channels:
  - conda-forge
dependencies:
  - python==3.12.*
  - conda-forge::ipywidgets==8.0.4
  - pip
  - pip:
    - cellpose==3.0.7
    - matplotlib==3.7.1
    - ome-zarr==0.14.0
    - pandas==3.0.2
    - jupyter==1.0.0 # if using notebooks. This can be omitted if using the script
    